name: github-actions-docker-compose-fly.io

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{secrets.KOYEB_API_TOKEN}}"
      

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: glowberry-tax-structure-simulator-gha-docker-compose-koyeb
          service-name: glowberry-tax-structure-simulator-gha-docker-compose-koyeb
          service-instance-type: free
          git-builder: docker
          git-docker-dockerfile: Dockerfile.koyeb
          service-env: PORT=3000
          service-ports: "3000:http"
          service-routes: "/:3000"